Repository asyncapi/spec, pull requests merged in 2021-12, with the labels that each got.

#672 chore: fix codeowners file to enable people to also decide and not just bot :smile:
  CODEOWNERS
Labels: ready-to-merge

#653 docs: clarify bundling behavior on Schema Object
  spec/asyncapi.md
Labels: ✏️ Editorial, ready-to-merge

#651 docs: small social media system example
  examples/social-media/backend/asyncapi.yaml
  examples/social-media/comments-service/asyncapi.yaml
  examples/social-media/common/messages.yaml
  examples/social-media/common/schemas.yaml
  examples/social-media/frontend/asyncapi.yaml
  examples/social-media/notification-service/asyncapi.yaml
  examples/social-media/public-api/asyncapi.yaml
  examples/social-media/readme.md
Labels: ready-to-merge

#648 docs: change `clientId` type on kafka operation to schema
  examples/streetlights-kafka.yml
Labels: ✏️ Editorial, ready-to-merge

#676 chore: update release branch
  .releaserc
  examples/anyof.yml
  examples/application-headers.yml
  examples/correlation-id.yml
  examples/gitter-streaming.yml
  examples/mercure.yml
  examples/not.yml
  examples/oneof.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/simple.yml
  examples/slack-rtm.yml
  examples/streetlights-kafka.yml
  examples/streetlights-mqtt.yml
  examples/websocket-gemini.yml
Labels: autoapproved, ready-to-merge
