Repository asyncapi/spec, pull requests merged in 2021-07, with the labels that each got.

#589 docs: document missed server variable in the example
  spec/asyncapi.md
Labels: ✏️ Editorial, 🐞 Bug

#598 ci: fix update-spec workflow
  .github/workflows/new-spec-release.yml
  .github/workflows/update-spec.yaml
Labels: 🐞 Bug

#592 docs: remove trailing commas from examples
  spec/asyncapi.md
Labels: ✏️ Editorial

#593 docs: all links should use secure protocol
  spec/asyncapi.md
Labels: ✏️ Editorial
