Repository asyncapi/spec, pull requests merged in 2022-01, with the labels that each got.

#642 docs: use proper term for {} characters
  spec/asyncapi.md
Labels: ready-to-merge

#603 docs: fix the type and docs of Operation.message field
  spec/asyncapi.md
Labels: ✏️ Editorial, ready-to-merge

#665 feat: allow servers and channels to be defined as components
  examples/social-media/backend/asyncapi.yaml
  examples/social-media/common/servers.yaml
  examples/social-media/frontend/asyncapi.yaml
  spec/asyncapi.md
Labels: 🏁 Accepted (RFC 3), ready-to-merge

#700 docs: fix <br> tags that break building asyncapi website
  spec/asyncapi.md
Labels: ready-to-merge

#681 feat: release version 2.3.0
  .releaserc
  examples/anyof.yml
  examples/application-headers.yml
  examples/correlation-id.yml
  examples/gitter-streaming.yml
  examples/mercure.yml
  examples/not.yml
  examples/oneof.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/simple.yml
  examples/slack-rtm.yml
  examples/social-media/backend/asyncapi.yaml
  examples/social-media/common/servers.yaml
  examples/social-media/frontend/asyncapi.yaml
  examples/streetlights-kafka.yml
  examples/streetlights-mqtt.yml
  examples/websocket-gemini.yml
  spec/asyncapi.md
Labels: autoapproved, ready-to-merge
