Repository asyncapi/spec, pull requests merged in 2022-04, with the labels that each got.

#756 docs: autoupdate label step for RELEASE_PROCESS.md
  RELEASE_PROCESS.md
Labels: ready-to-merge

#584 feat: add security at the operation level
  examples/operation-security.yml
  examples/streetlights-operation-security.yml
  spec/asyncapi.md
Labels: 📄 Draft (RFC 2), ready-to-merge, autoupdate

#758 chore: update with upstream master
  .all-contributorsrc
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/add-good-first-issue-labels.yml
  .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
  .github/workflows/automerge-for-humans-merging.yml
  .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml
  .github/workflows/automerge-orphans.yml
  .github/workflows/automerge.yml
  .github/workflows/autoupdate.yml
  .github/workflows/bump.yml
  .github/workflows/help-command.yml
  .github/workflows/if-go-pr-testing.yml
  .github/workflows/if-nodejs-pr-testing.yml
  .github/workflows/if-nodejs-release.yml
  .github/workflows/if-nodejs-version-bump.yml
  .github/workflows/issues-prs-notifications.yml
  .github/workflows/link-check-cron.yml
  .github/workflows/link-check-pr.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/notify-tsc-members-mention.yml
  .github/workflows/release-announcements.yml
  .github/workflows/sentiment-analysis.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/welcome-first-time-contrib.yml
  .releaserc
  README.md
  RELEASE_PROCESS.md
  assets/logo.png
  spec/asyncapi.md
Labels: ready-to-merge

#757 docs: add server definition in spec
  spec/asyncapi.md
Labels: ready-to-merge

#717 feat: added server variable object as reusable object
  spec/asyncapi.md
Labels: 🏁 Accepted (RFC 3), ready-to-merge

#753 chore: update release branch to 3.0
  README.md
  examples/anyof.yml
  examples/application-headers.yml
  examples/correlation-id.yml
  examples/gitter-streaming.yml
  examples/mercure.yml
  examples/not.yml
  examples/oneof.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/simple.yml
  examples/slack-rtm.yml
  examples/social-media/backend/asyncapi.yaml
  examples/social-media/comments-service/asyncapi.yaml
  examples/social-media/frontend/asyncapi.yaml
  examples/social-media/notification-service/asyncapi.yaml
  examples/social-media/public-api/asyncapi.yaml
  examples/streetlights-kafka.yml
  examples/streetlights-mqtt.yml
  examples/websocket-gemini.yml
  spec/asyncapi.md
Labels: ready-to-merge

#751 feat: add messageId property
  spec/asyncapi.md
Labels: ready-to-merge

#772 chore: fix merge conflicts with `master` branch
  .all-contributorsrc
  .github/workflows/add-good-first-issue-labels.yml
  .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
  .github/workflows/automerge-for-humans-merging.yml
  .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml
  .github/workflows/automerge-orphans.yml
  .github/workflows/automerge.yml
  .github/workflows/autoupdate.yml
  .github/workflows/bump.yml
  .github/workflows/help-command.yml
  .github/workflows/if-go-pr-testing.yml
  .github/workflows/if-nodejs-pr-testing.yml
  .github/workflows/if-nodejs-release.yml
  .github/workflows/if-nodejs-version-bump.yml
  .github/workflows/issues-prs-notifications.yml
  .github/workflows/link-check-cron.yml
  .github/workflows/link-check-pr.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/notify-tsc-members-mention.yml
  .github/workflows/release-announcements.yml
  .github/workflows/sentiment-analysis.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/welcome-first-time-contrib.yml
  README.md
  RELEASE_PROCESS.md
  spec/asyncapi.md
Labels: ready-to-merge

#773 chore: fix merge conflict
  README.md
Labels: ready-to-merge
