Repository asyncapi/spec, pull requests merged in 2022-06, with the labels that each got.

#770 docs(release): update list of tools and maintainers to notify when releasing
  RELEASE_PROCESS.md
Labels: ready-to-merge

#801 ci: updating spec urls to match new Information Architecture in website
  .github/scripts/remove-toc.js
  .github/workflows/new-spec-release.yml
  .github/workflows/update-spec.yaml
Labels: ready-to-merge

#769 docs: fix links in Markdown files
  RELEASE_PROCESS.md
  mlc_config.json
Labels: ready-to-merge, do-not-merge

#807 chore: merge next-major-spec with latest master
  .all-contributorsrc
  .github/scripts/remove-toc.js
  .github/workflows/add-good-first-issue-labels.yml
  .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
  .github/workflows/automerge-orphans.yml
  .github/workflows/autoupdate.yml
  .github/workflows/help-command.yml
  .github/workflows/link-check-cron.yml
  .github/workflows/link-check-pr.yml
  .github/workflows/new-spec-release.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/update-spec.yaml
  .releaserc
  CODE_OF_CONDUCT.md
  README.md
  RELEASE_PROCESS.md
  assets/release_process/create_branch.png
  examples/operation-security.yml
  examples/social-media/common/messages.yaml
  examples/streetlights-operation-security.yml
  mlc_config.json
  spec/asyncapi.md
Labels: autoupdate

#659 docs: adapting release process to new definition setup
  RELEASE_PROCESS.md
Labels: ready-to-merge

#718 docs: fix URN examples
  examples/gitter-streaming.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/slack-rtm.yml
  spec/asyncapi.md
Labels: ready-to-merge

#810 chore: update `next-spec` branch with latest changes from `master`
  .all-contributorsrc
  .github/scripts/remove-toc.js
  .github/workflows/automerge-orphans.yml
  .github/workflows/autoupdate.yml
  .github/workflows/help-command.yml
  .github/workflows/link-check-cron.yml
  .github/workflows/new-spec-release.yml
  .github/workflows/stale-issues-prs.yml
  .github/workflows/update-spec.yaml
  .releaserc
  CODE_OF_CONDUCT.md
  README.md
  RELEASE_PROCESS.md
  assets/release_process/create_branch.png
  examples/gitter-streaming.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/slack-rtm.yml
  examples/social-media/common/messages.yaml
  mlc_config.json
  spec/asyncapi.md
Labels: ready-to-merge

#808 chore: set 2.5.0 as the latest version of the spec
  README.md
  examples/anyof.yml
  examples/application-headers.yml
  examples/correlation-id.yml
  examples/gitter-streaming.yml
  examples/mercure.yml
  examples/not.yml
  examples/oneof.yml
  examples/operation-security.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/simple.yml
  examples/slack-rtm.yml
  examples/streetlights-kafka.yml
  examples/streetlights-mqtt.yml
  examples/streetlights-operation-security.yml
  examples/websocket-gemini.yml
  spec/asyncapi.md
Labels: ready-to-merge
