Repository asyncapi/spec, pull requests merged in 2023-01, with the labels that each got.

#852 feat: unify all referencing mechanisms
  spec/asyncapi.md
Labels: 💡 Proposal (RFC 1), ready-to-merge

#875 chore: clarify introduction
  spec/asyncapi.md
Labels: ✏️ Editorial, ready-to-merge

#895 chore: update release branch
  README.md
  examples/anyof.yml
  examples/application-headers.yml
  examples/correlation-id.yml
  examples/gitter-streaming.yml
  examples/mercure.yml
  examples/not.yml
  examples/oneof.yml
  examples/operation-security.yml
  examples/rpc-client.yml
  examples/rpc-server.yml
  examples/simple.yml
  examples/slack-rtm.yml
  examples/social-media/backend/asyncapi.yaml
  examples/social-media/comments-service/asyncapi.yaml
  examples/social-media/frontend/asyncapi.yaml
  examples/social-media/notification-service/asyncapi.yaml
  examples/social-media/public-api/asyncapi.yaml
  examples/streetlights-kafka.yml
  examples/streetlights-mqtt.yml
  examples/streetlights-operation-security.yml
  examples/websocket-gemini.yml
  spec/asyncapi.md
Labels: ready-to-merge

#882 feat: add Pulsar bindings to the specification.
  spec/asyncapi.md
Labels: 🏁 Accepted (RFC 3), ready-to-merge

#901 chore: update release branch
  .github/workflows/add-good-first-issue-labels.yml
  .github/workflows/scripts/mailchimp/package-lock.json
Labels: ready-to-merge

#903 chore: update release branch
  .github/workflows/scripts/mailchimp/package-lock.json
Labels: ready-to-merge

#904 chore: another update of release branch
  .github/workflows/add-good-first-issue-labels.yml
Labels: ready-to-merge
