Repository asyncapi/spec, pull requests merged in 2024-02, with the labels that each got.

#1001 docs: operation trait object description
  spec/asyncapi.md
Labels: 🤷‍♀️ Ambiguity, ready-to-merge

#1018 docs: explain Multi Format Schema Object option in Schema Object
  spec/asyncapi.md
Labels: ready-to-merge

#1033 docs: add missing reference to Version 3.0.0 in README
  README.md
Labels: ready-to-merge

#1034 docs: fix adeo-kafka-request-reply-asyncapi.yml
  examples/adeo-kafka-request-reply-asyncapi.yml
Labels: ready-to-merge

#1035 docs: fix Specification Extensions Field Pattern
  spec/asyncapi.md
Labels: ready-to-merge

#1004 docs: fix markdown linter issues
  spec/asyncapi.md
Labels: ✏️ Editorial, ready-to-merge

#1032 docs: add example "Multi Format Schema Object Example with Avro"
  spec/asyncapi.md
Labels: ready-to-merge
